language: node_js
node_js:
  - 8.1.4
services:
  - postgresql
before_install:
  - npm install sequelize-cli -g
before_script:
  - psql -c 'create database "doc-manager-test";' -U postgres

script: "npm test"

after_success: "npm run test:coverage"